### ISSUE TITLE
Use EncodeUri() if part of the URL path or EncodeUriComponent() if used as a URL parameter

### ISSUE THREAD

**Issue by semisight** [AudienceTalkingGroup/Talkie-by-Audience-Talking---GTM-Template#1]
https://github.com/AudienceTalkingGroup/Talkie-by-Audience-Talking---GTM-Template/blob/72ddb0e25d19323bf1d5eacae2b59d7170a8a96e/template.tpl#L172

When reviewing your template we've noticed that it is using parameters to build a url. It's a best practice to use [[EncodeUri()](https://developers.google.com/tag-manager/templates/api#encodeuri)](https://developers.google.com/tag-manager/templates/api#encodeuri) if part of the URL path or [[EncodeUriComponent()](https://developers.google.com/tag-manager/templates/api#encodeuricomponent)](https://developers.google.com/tag-manager/templates/api#encodeuricomponent) if used as a URL parameter.

**Comment by pyrob** [comment]
Thanks Alex!!

We build an URL that is a src of JS script to append in the page. So, we already encodeURIComponent parameters of URL like "atpu", "atru" or "cp", but, we cannot encodeURIComponent domain and other parameters like schema "https" because it won't load correctly.

Could you check it again?

Have a nice day

**Comment by semisight** [comment]
Hiya @pyrob! Apologies for leaving this issue open for so long. I lost it at the bottom of my Github notification queue :(

In this case, the variables that I see that should be encoded are:

1. `atid` -- this is a TEXT input so it definitely needs to be encoded
1. `cc[0]` -- as the expression `getCookieValues('atleadid')` can return a non-numeric value (alternatively, you can call `makeNumber(getCookieValues('atleadid'))` and that will work)
1. `atru` -- it should maybe be encoded but I won't block on this one [on this code path](https://github.com/AudienceTalkingGroup/Talkie-by-Audience-Talking---GTM-Template/blob/72ddb0e25d19323bf1d5eacae2b59d7170a8a96e/template.tpl#L165)

Will encoding those affect the performance of the tag?

**Comment by pyrob** [comment]
Hi @semisight, thanks for your reply.

I already upload a new commit with the changes that you mention. Hope everything is ok now.

Thank you and have a nice day

**Comment by semisight** [comment]
Nice, I've merged this into Gallery.
